---
- name: Copy Drupal 7 Database from Local Host to Remote Host.
  hosts: drupal7
  gather_facts: false

  vars_files:
    - vars/drupal7.yml

  vars:
    site_name: "dpa"
    # site_name: "sfdbi"

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  tasks:
    - name: Verify terminus is installed.
      command: terminus --version
      delegate_to: 127.0.0.1
      changed_when: false

    # See: https://docs.pantheon.io/terminus/commands/local-getLiveDB
    - name: Export the database to $HOME/pantheon-local-copies/db/{{ site_name }}-db.tgz.
      shell: "terminus local:getLiveDB --no-interaction --overwrite -- {{ site_name }}"
      delegate_to: 127.0.0.1

    # See: https://docs.pantheon.io/terminus/commands/local-getLiveFiles
    - name: Export the files to $HOME/pantheon-local-copies/files/{{ site_name }}-files.tgz.
      shell: "terminus local:getLiveFiles --no-interaction --overwrite -- {{ site_name }}"
      delegate_to: 127.0.0.1

    # See: https://docs.pantheon.io/terminus/commands/local-clone
    # - name: Export the site to $HOME/pantheon-local-copies/{{ site_name }}.
    #   shell: "terminus local:clone --no-interaction --override -- {{ site_name }}"
    #   delegate_to: 127.0.0.1
