---
- name: Export Pantheon Site.
  hosts: 127.0.0.1
  gather_facts: false

  vars_files:
    - vars/drupal.yml

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

    - name: Set home var to "{{ lookup('env', 'HOME') }}".
      ansible.builtin.set_fact:
        home: "{{ lookup('env', 'HOME') }}"

    - name: Print home var.
      debug: var=home

    - name: Set home_pantheon_local_copies_dir var to "{{ home }}/pantheon-local-copies".
      ansible.builtin.set_fact:
        home_pantheon_local_copies_dir: "{{ home }}/pantheon-local-copies"

  tasks:
    - name: Verify terminus is installed.
      command: terminus --version
      changed_when: false

    # See: https://docs.pantheon.io/terminus/commands/local-getLiveDB
    - name: Export the database to {{ home_pantheon_local_copies_dir }}/db/{{ site_name }}-db.tgz.
      shell: "terminus local:getLiveDB --no-interaction --overwrite -- {{ site_name }}"

    # See: https://docs.pantheon.io/terminus/commands/local-getLiveFiles
    - name: Export the files to {{ home_pantheon_local_copies_dir }}/files/{{ site_name }}-files.tgz.
      shell: "terminus local:getLiveFiles --no-interaction --overwrite -- {{ site_name }}"

    # See: https://docs.pantheon.io/terminus/commands/local-clone
    - name: Export the site to {{ home_pantheon_local_copies_dir }}/{{ site_name }}.
      shell: "terminus local:clone --no-interaction --override -- {{ site_name }}"

    - name: Create a tar.gz archive of the site source and save to {{ home_pantheon_local_copies_dir }}/source/{{ site_name }}-source.tar.gz.
      shell: |
        mkdir -p {{ home_pantheon_local_copies_dir }}/source

        pushd {{ home_pantheon_local_copies_dir }} &&
          tar -cvzf {{ site_name }}-source.tar.gz {{ site_name }}/* &&
          popd

        mv {{ home_pantheon_local_copies_dir }}/{{ site_name }}-source.tar.gz {{ home_pantheon_local_copies_dir }}/source/{{ site_name }}-source.tar.gz
      args:
        creates: "{{ home_pantheon_local_copies_dir }}/source/{{ site_name }}-source.tar.gz"
