---
- name: Setup Drupal 7.
  hosts: drupal7.ec2
  become: true

  vars_files:
    - vars/drupal7.yml

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Ensure directory /var/www/html exists and has correct permissions.
      file:
        path: /var/www/html
        owner: root
        group: root
        mode: '0755'
        state: directory

    - name: Download and unarchive drupal.
      unarchive:
        src: https://ftp.drupal.org/files/projects/drupal-7.99.tar.gz
        dest: /tmp
        owner: root
        group: root
        remote_src: yes
        creates: /tmp/drupal-7.99

    - name: Copy a "sudoers" file on the remote machine for editing.
      copy:
        src: /tmp/drupal-7.99
        dest: /var/www/html/drupal
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: yes

  roles:
    - role: geerlingguy.apache

  post_tasks:
    - name: Verify Apache is installed.
      command: apache2 -v
      changed_when: false
