---
- name: Setup Drupal Dependencies.
  hosts: drupal
  become: true

  vars_files:
    - vars/drupal.yml

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

    - name: Update apt cache.
      ansible.builtin.apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql
    - role: geerlingguy.phpmyadmin
    - role: geerlingguy.composer
    - role: geerlingguy.drush

  post_tasks:
    - name: Verify Apache is installed.
      ansible.builtin.command: apache2 -v
      changed_when: false

    - name: Verify MySQL is installed.
      ansible.builtin.command: mysql --version
      changed_when: false

    - name: Verify PHP is installed.
      ansible.builtin.command: php -v
      changed_when: false

    - name: Verify PHP version is correct.
      ansible.builtin.shell: php -v | grep -F '{{ php_version }}'
      changed_when: false

    - name: Ensure phpMyAdmin is running.
      uri:
        url: "http://127.0.0.1/phpmyadmin/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1


- name: Install Drupal CMS.
  hosts: drupal
  become: true

  vars_files:
    - vars/drupal.yml

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

    - name: Update apt cache.
      ansible.builtin.apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.drupal
