---
- name: Setup Drupal 7 Dependencies.
  hosts: drupal7
  become: true

  vars_files:
    - vars/drupal7.yml

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php-versions
    - role: geerlingguy.php

  post_tasks:
    - name: Verify Apache is installed.
      command: apache2 -v
      changed_when: false

    - name: Verify Mysql is installed.
      command: mysql --version
      changed_when: false

    - name: Verify PHP is installed.
      command: php -v
      changed_when: false

    - name: Verify PHP version is correct.
      shell: php -v | grep -F '{{ php_version }}'
      changed_when: false


- name: Install Drupal 7.
  hosts: drupal7
  become: true

  vars_files:
    - vars/drupal7.yml

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

    - import_tasks: tasks/download-unpack-drupal.yml
