---
- name: Export.
  hosts: drupal
  gather_facts: false

  tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

    - name: Verify terminus is installed.
      command: terminus --version
      delegate_to: 127.0.0.1
      changed_when: false

    # https://docs.pantheon.io/terminus/commands/local-getLiveDB
    - name: Backup the database to $HOME/pantheon-local-copies/db.
      shell: |
        terminus local:getLiveDB --overwrite -- foo
      delegate_to: 127.0.0.1
