---
- name: Export a Pantheon Site to $HOME/pantheon-local-copies.
  hosts: drupal
  gather_facts: false

  vars:
    site: dpa

  tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

    - name: Verify terminus is installed.
      command: terminus --version
      delegate_to: 127.0.0.1
      changed_when: false

    # https://docs.pantheon.io/terminus/commands/local-getLiveDB
    - name: Export the database to $HOME/pantheon-local-copies/db/{{ site }}-db.tgz.
      shell: terminus local:getLiveDB --no-interaction --overwrite -- {{ site }}
      delegate_to: 127.0.0.1

    # https://docs.pantheon.io/terminus/commands/local-getLiveFiles
    - name: Export the files to $HOME/pantheon-local-copies/files/{{ site }}-files.tgz.
      shell: terminus local:getLiveFiles --no-interaction --overwrite -- {{ site }}
      delegate_to: 127.0.0.1

    # https://docs.pantheon.io/terminus/commands/local-clone
    - name: Export the site to $HOME/pantheon-local-copies/{{ site }}.
      shell: terminus local:clone --no-interaction --override -- {{ site }}
      delegate_to: 127.0.0.1
