---
- name: Upgrade.
  hosts: drupal
  gather_facts: false
  become: true

  tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

    - name: Upgrade all software.
      apt:
        update_cache: true
        upgrade: dist

    - name: Check if a reboot is required.
      stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the machine (if required).
      reboot:
        reboot_timeout: 300
      when: reboot_required_file.stat.exists == true
      tags:
        - reboot

    - name: Remove dependencies that are no longer required.
      apt:
        autoremove: yes
